plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

version = '1.0'
group = 'fr.shoqapik.blockend' // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = 'BlockEnd'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
minecraft {
    mappings channel: 'official', version: '1.19.2'
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'blockend'

            arg "-mixin.config=blockend.mixins.json"
            property "mixin.env.remapRefMap", "true"

            mods {
                blockend {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'blockend'

            arg "-mixin.config=blockend.mixins.json"
            property "mixin.env.remapRefMap", "true"
            mods {
                blockend {
                    source sourceSets.main
                }
            }
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            property 'forge.enabledGameTestNamespaces', 'blockend'

            mods {
                blockend {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            args '--mod', 'blockend', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                blockend {
                    source sourceSets.main
                }
            }
        }
    }
}
tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }

}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    implementation fg.deobf("curse.maven:stoneworks-852663:5049592")
    implementation fg.deobf("curse.maven:big-extras-forge-499948:4713352")
    implementation fg.deobf("curse.maven:cataclysmic-combat-880483:5790282")
    implementation fg.deobf("curse.maven:woodworks-543610:4776123")
    implementation fg.deobf("curse.maven:additional-lanterns-501590:5275363")
    implementation fg.deobf("curse.maven:upgrade-aquatic-326895:4777515")
    implementation fg.deobf("curse.maven:experience-obelisk-579484:5733667")
    implementation fg.deobf("curse.maven:occultism-361026:5137571")
    implementation fg.deobf("curse.maven:summoningrituals-671040:4664059")
    implementation fg.deobf("curse.maven:decorative-blocks-362528:3941638")
    implementation fg.deobf("curse.maven:quark-243121:4812006")
    implementation fg.deobf("curse.maven:extended-slabs-plus-374492:4522949")
    implementation fg.deobf("curse.maven:selene-499980:5567102")
    implementation fg.deobf("curse.maven:blueprint-382216:4749000")
    implementation fg.deobf("curse.maven:smartbrainlib-661293:4458565")
    implementation fg.deobf("curse.maven:curios-309927:5494603")
    implementation fg.deobf("curse.maven:supermartijn642s-core-lib-454372:5668843")
    implementation fg.deobf("curse.maven:puzzles-lib-495476:4600775")
    implementation fg.deobf("curse.maven:autoreglib-250363:4100299")
    implementation fg.deobf("curse.maven:cloth-config-348521:5729096")
    implementation fg.deobf("curse.maven:moving-elevators-373051:5686455")
    implementation fg.deobf("curse.maven:supermartijn642s-config-lib-438332:4715406")
    implementation fg.deobf("curse.maven:moving-elevators-extra-remote-panels-addon-937449:4867548")
    implementation fg.deobf("curse.maven:modonomicon-538392:4675974")
    implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.19:3.1.40')
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}


mixin {

    // MixinGradle Settings
    add sourceSets.main, 'blockend.refmap.json'
    config 'blockend.mixins.json'

}


// Example for how to get properties into the manifest for reading at runtime.
jar {
    manifest {
        attributes([
                "Specification-Title"     : "blockend",
                "Specification-Vendor"    : "blockendsareus",
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "blockendsareus",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "MixinConfigs": mod_id+".mixins.json"

        ])
    }
}

// Example configuration to allow publishing using the maven-publish plugin
// This is the preferred method to reobfuscate your jar file
jar.finalizedBy('reobfJar')
// However if you are in a multi-project build, dev time needs unobfed jar files, so you can delay the obfuscation until publishing by doing
// publish.dependsOn('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}
